%Alberto Ferreiro Campello
%Calculo de la letra del DNI

%Cálculo: se calcula el resto de dividir el valor numerico del DNI entre 23.
%Existen tablas que muestran la correspondencia entre el resto y la letra.

function letradni(dni)
  a=(rem(dni,23 ));
  if (a==0)
    disp('T')
  elseif (a==1)
    disp('R')
  elseif (a==2)
    disp('W')
  elseif (a==3)
    disp('A')
  elseif (a==4)
    disp('G')
  elseif (a==5)
    disp('M')
  elseif (a==6)
    disp('Y')
  elseif (a==7)
    disp('F')
  elseif (a==8)
    disp('P')
  elseif (a==9)
    disp('D')
  elseif (a==10)
    disp('X')
  elseif (a==11)
    disp('B')
  elseif (a==12)
    disp('N')
  elseif (a==13)
    disp('J')
  elseif (a==14)
    disp('Z')
  elseif (a==15)
    disp('S')
  elseif (a==16)
    disp('Q')
  elseif (a==17)
    disp('V')
  elseif (a==18)
    disp('H')
  elseif (a==19)
    disp('L')
  elseif (a==20)
    disp('C')
  elseif (a==21)
    disp('K')
  elseif (a==22)
    disp('E')
  else disp('error')
  end